package com.telemedicina.prescription.model;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.Instant;

@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class Prescription {
    private Long id;
    private Long consultationId;
    private Long patientId;
    private Long doctorId;       // null daca e generata automat de sistem
    private Long diagnosisId;
    private Instant issuedAt;
    private Instant validUntil;
    private Boolean isAutoGenerated;
    private String status;
}