package com.telemedicina.prescription.dto.response;

import lombok.Builder;
import lombok.Data;

import java.time.Instant;
import java.util.List;

@Data
@Builder
public class PrescriptionResponse {
    private Long id;
    private Long consultationId;
    private Long patientId;
    private Long doctorId;          // null daca e generata automat
    private Long diagnosisId;
    private Instant issuedAt;
    private Instant validUntil;
    private Boolean isAutoGenerated;
    private String status;

    private List<MedicationResponse> medications;
    @Data
    @Builder
    public static class MedicationResponse {
        private Long id;
        private String medicationName;
        private String dosage;
        private String frequency;
        private Integer durationDays;
        private String instructions;
    }
}