package com.telemedicina.prescription.mapper;

import com.telemedicina.prescription.dto.response.PrescriptionResponse;
import com.telemedicina.prescription.dto.response.ReferralResponse;
import com.telemedicina.prescription.model.Prescription;
import com.telemedicina.prescription.model.PrescriptionMedication;
import com.telemedicina.prescription.model.Referral;
import org.springframework.stereotype.Component;

import java.util.List;
import java.util.stream.Collectors;

@Component
public class PrescriptionMapper {

    // reteta + medicamentele ei combinate intr-un singur response
    public PrescriptionResponse toResponse(Prescription p, List<PrescriptionMedication> medications) {
        return PrescriptionResponse.builder()
                .id(p.getId())
                .consultationId(p.getConsultationId())
                .patientId(p.getPatientId())
                .doctorId(p.getDoctorId())
                .diagnosisId(p.getDiagnosisId())
                .issuedAt(p.getIssuedAt())
                .validUntil(p.getValidUntil())
                .isAutoGenerated(p.getIsAutoGenerated())
                .status(p.getStatus())
                .medications(medications.stream()
                        .map(this::toMedicationResponse)
                        .collect(Collectors.toList()))
                .build();
    }

    private PrescriptionResponse.MedicationResponse toMedicationResponse(PrescriptionMedication m) {
        return PrescriptionResponse.MedicationResponse.builder()
                .id(m.getId())
                .medicationName(m.getMedicationName())
                .dosage(m.getDosage())
                .frequency(m.getFrequency())
                .durationDays(m.getDurationDays())
                .instructions(m.getInstructions())
                .build();
    }

    public ReferralResponse toReferralResponse(Referral r) {
        return ReferralResponse.builder()
                .id(r.getId())
                .consultationId(r.getConsultationId())
                .patientId(r.getPatientId())
                .doctorId(r.getDoctorId())
                .referralType(r.getReferralType())
                .priority(r.getPriority())
                .destination(r.getDestination())
                .reason(r.getReason())
                .issuedAt(r.getIssuedAt())
                .build();
    }
}