package com.telemedicina.prescription.repository;

import com.telemedicina.prescription.model.Prescription;
import com.telemedicina.prescription.model.PrescriptionMedication;
import com.telemedicina.prescription.model.Referral;

import java.util.List;
import java.util.Optional;

public interface PrescriptionRepository {

    //retete
    Optional<Prescription> findById(Long id);
    List<Prescription> findAllByPatientId(Long patientId);
    Optional<Prescription> findByConsultationId(Long consultationId);

    Long createPrescription(Long consultationId, Long patientId, Long doctorId,
                            Long diagnosisId, int validDays, boolean isAutoGenerated);
    void addMedication(Long prescriptionId, String medicationName, String dosage,
                       String frequency, Integer durationDays, String instructions);

    List<PrescriptionMedication> findMedications(Long prescriptionId);

    //trimiteri
    Optional<Referral> findReferralById(Long id);
    List<Referral> findReferralsByPatientId(Long patientId);
    List<Referral> findReferralsByConsultationId(Long consultationId);

    Long createReferral(Long consultationId, Long patientId, Long doctorId,
                        String referralType, String priority, String destination, String reason);

    //doctor
    Optional<Long> findDoctorIdByUserId(Long userId);
}