package com.telemedicina.prescription.repository;

import com.telemedicina.prescription.model.Prescription;
import com.telemedicina.prescription.model.PrescriptionMedication;
import com.telemedicina.prescription.model.Referral;
import com.telemedicina.prescription.model.ReferralPriority;
import com.telemedicina.prescription.model.ReferralType;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.core.RowMapper;
import org.springframework.stereotype.Repository;

import java.util.List;
import java.util.Optional;

@Slf4j
@Repository
@RequiredArgsConstructor
public class PrescriptionRepositoryImpl implements PrescriptionRepository {

    private final JdbcTemplate jdbc;

    @Override
    public Optional<Prescription> findById(Long id) {
        List<Prescription> result = jdbc.query(
                "SELECT * FROM prescriptions WHERE id = ?",
                prescriptionRowMapper(), id
        );
        return result.isEmpty() ? Optional.empty() : Optional.of(result.get(0));
    }

    @Override
    public List<Prescription> findAllByPatientId(Long patientId) {
        return jdbc.query(
                "SELECT * FROM prescriptions WHERE patient_id = ? ORDER BY issued_at DESC",
                prescriptionRowMapper(), patientId
        );
    }

    @Override
    public Optional<Prescription> findByConsultationId(Long consultationId) {
        List<Prescription> result = jdbc.query(
                "SELECT * FROM prescriptions WHERE consultation_id = ?",
                prescriptionRowMapper(), consultationId
        );
        return result.isEmpty() ? Optional.empty() : Optional.of(result.get(0));
    }

    @Override
    public Long createPrescription(Long consultationId, Long patientId, Long doctorId,
                                   Long diagnosisId, int validDays, boolean isAutoGenerated) {
        return jdbc.queryForObject(
                "INSERT INTO prescriptions (consultation_id, patient_id, doctor_id, diagnosis_id, " +
                        "valid_until, is_auto_generated) " +
                        "VALUES (?, ?, ?, ?, NOW() + (? || ' days')::INTERVAL, ?) RETURNING id",
                Long.class,
                consultationId, patientId, doctorId, diagnosisId, validDays, isAutoGenerated
        );
    }

    @Override
    public void addMedication(Long prescriptionId, String medicationName, String dosage,
                              String frequency, Integer durationDays, String instructions) {
        jdbc.update(
                "INSERT INTO prescription_medications " +
                        "(prescription_id, medication_name, dosage, frequency, duration_days, instructions) " +
                        "VALUES (?, ?, ?, ?, ?, ?)",
                prescriptionId, medicationName, dosage, frequency, durationDays, instructions
        );
    }

    @Override
    public List<PrescriptionMedication> findMedications(Long prescriptionId) {
        return jdbc.query(
                "SELECT * FROM prescription_medications WHERE prescription_id = ?",
                medicationRowMapper(), prescriptionId
        );
    }

    @Override
    public Optional<Referral> findReferralById(Long id) {
        List<Referral> result = jdbc.query(
                "SELECT * FROM referrals WHERE id = ?",
                referralRowMapper(), id
        );
        return result.isEmpty() ? Optional.empty() : Optional.of(result.get(0));
    }

    @Override
    public List<Referral> findReferralsByPatientId(Long patientId) {
        return jdbc.query(
                "SELECT * FROM referrals WHERE patient_id = ? ORDER BY issued_at DESC",
                referralRowMapper(), patientId
        );
    }

    @Override
    public List<Referral> findReferralsByConsultationId(Long consultationId) {
        return jdbc.query(
                "SELECT * FROM referrals WHERE consultation_id = ?",
                referralRowMapper(), consultationId
        );
    }

    @Override
    public Long createReferral(Long consultationId, Long patientId, Long doctorId,
                               String referralType, String priority, String destination, String reason) {
        return jdbc.queryForObject(
                "INSERT INTO referrals (consultation_id, patient_id, doctor_id, referral_type, " +
                        "priority, destination, reason) VALUES (?, ?, ?, ?::referral_type, ?::referral_priority, ?, ?) " +
                        "RETURNING id",
                Long.class,
                consultationId, patientId, doctorId, referralType, priority, destination, reason
        );
    }

    @Override
    public Optional<Long> findDoctorIdByUserId(Long userId) {
        List<Long> result = jdbc.query(
                "SELECT id FROM doctors WHERE user_id = ?",
                (rs, rowNum) -> rs.getLong("id"),
                userId
        );
        return result.isEmpty() ? Optional.empty() : Optional.of(result.get(0));
    }

    // ================================================================
    // ROW MAPPERS
    // ================================================================

    private RowMapper<Prescription> prescriptionRowMapper() {
        return (rs, rowNum) -> Prescription.builder()
                .id(rs.getLong("id"))
                .consultationId(rs.getLong("consultation_id"))
                .patientId(rs.getLong("patient_id"))
                .doctorId(rs.getObject("doctor_id") != null ? rs.getLong("doctor_id") : null)
                .diagnosisId(rs.getObject("diagnosis_id") != null ? rs.getLong("diagnosis_id") : null)
                .issuedAt(rs.getTimestamp("issued_at") != null
                        ? rs.getTimestamp("issued_at").toInstant() : null)
                .validUntil(rs.getTimestamp("valid_until") != null
                        ? rs.getTimestamp("valid_until").toInstant() : null)
                .isAutoGenerated(rs.getBoolean("is_auto_generated"))
                .status(rs.getString("status"))
                .build();
    }

    private RowMapper<PrescriptionMedication> medicationRowMapper() {
        return (rs, rowNum) -> PrescriptionMedication.builder()
                .id(rs.getLong("id"))
                .prescriptionId(rs.getLong("prescription_id"))
                .medicationName(rs.getString("medication_name"))
                .dosage(rs.getString("dosage"))
                .frequency(rs.getString("frequency"))
                .durationDays(rs.getObject("duration_days") != null ? rs.getInt("duration_days") : null)
                .instructions(rs.getString("instructions"))
                .build();
    }

    private RowMapper<Referral> referralRowMapper() {
        return (rs, rowNum) -> Referral.builder()
                .id(rs.getLong("id"))
                .consultationId(rs.getLong("consultation_id"))
                .patientId(rs.getLong("patient_id"))
                .doctorId(rs.getObject("doctor_id") != null ? rs.getLong("doctor_id") : null)
                .referralType(ReferralType.valueOf(rs.getString("referral_type")))
                .priority(ReferralPriority.valueOf(rs.getString("priority")))
                .destination(rs.getString("destination"))
                .reason(rs.getString("reason"))
                .issuedAt(rs.getTimestamp("issued_at") != null
                        ? rs.getTimestamp("issued_at").toInstant() : null)
                .build();
    }
}